version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - onceuponatime
    restart: "on-failure"


  db:
    image: kartoza/postgis:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - onceuponatime
    restart: "on-failure"

networks:
  onceuponatime:
    driver: bridge

volumes:
  postgres_data:
