# Generated by Django 4.1.7 on 2023-04-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
