# Generated by Django 4.1.7 on 2023-05-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/Default_profile_picture.png', upload_to='profile_pictures/'),
        ),
    ]
