# Generated by Django 4.1.7 on 2023-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geolocation_lat', models.FloatField(blank=True, null=True)),
                ('geolocation_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='author',
        ),
        migrations.RemoveField(
            model_name='story',
            name='geolocation_lat',
        ),
        migrations.RemoveField(
            model_name='story',
            name='geolocation_lon',
        ),
        migrations.AddField(
            model_name='story',
            name='geolocations',
            field=models.ManyToManyField(related_name='story_locations', to='story.location'),
        ),
    ]
