# Generated by Django 4.1.7 on 2023-04-30 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0004_mystory_delete_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyStory',
            new_name='Story',
        ),
    ]
