# Generated by Django 4.1.7 on 2023-05-21 00:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tag'),
        ),
    ]
