# Generated by Django 4.1.7 on 2023-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_alter_story_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_resolution',
            field=models.CharField(choices=[('SD', 'Single Date'), ('I', 'Interval'), ('M', 'Month'), ('Y', 'Year'), ('S', 'Season'), ('D', 'Decade')], default='SD', max_length=2),
        ),
    ]
