# Generated by Django 4.1.7 on 2023-05-23 00:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_story_date_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geolocation_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geolocation_lon',
        ),
        migrations.RemoveField(
            model_name='story',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='start_date',
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
