# Generated by Django 4.1.7 on 2023-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_remove_location_geolocation_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='decade',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='interval_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='interval_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='month_year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='season',
            field=models.CharField(blank=True, choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='single_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
