# Generated by Django 4.1.7 on 2023-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_story_decade_story_interval_end_story_interval_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='month_year',
        ),
        migrations.AddField(
            model_name='story',
            name='month',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
