# Generated by Django 4.1.7 on 2023-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_remove_story_month_year_story_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='interval_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='interval_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
