# Generated by Django 4.1.7 on 2023-05-23 01:52

from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_alter_story_interval_end_alter_story_interval_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_resolution',
            field=models.CharField(choices=[('single_date', 'Single Date'), ('interval', 'Interval'), ('month', 'Month'), ('year', 'Year'), ('season', 'Season'), ('decade', 'Decade')], default='single_date', max_length=20),
        ),

    ]
