# Generated by Django 4.1.7 on 2023-05-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_alter_story_date_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geolocation_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
