# Generated by Django 4.1.7 on 2023-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_location_geolocation_lat_location_geolocation_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geolocation_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geolocation_lon',
        ),
        migrations.AlterField(
            model_name='story',
            name='single_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
