# Generated by Django 4.1.7 on 2023-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
